#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

build_dir="${HYPRSPACES_BUILD_DIR:-build}"
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"

install_dir="${HYPRSPACES_INSTALL_DIR:-$data_home/hyprspaces}"
plugin_path="$install_dir/hyprspaces.so"

hyprland_conf="${HYPRSPACES_HYPRLAND_CONF:-$config_home/hypr/hyprland.conf}"
autoload_conf="${HYPRSPACES_PLUGIN_CONF:-$config_home/hypr/hyprspaces-plugin.conf}"

usage() {
    cat <<'EOF'
Usage: scripts/plugin-install.sh <command>

Commands:
  install   Build plugin, install to user dir, enable autoload, and load now
  enable    Enable autoload and load plugin in current session
  disable   Disable autoload and unload plugin in current session
  remove    Disable autoload and remove installed plugin files

Environment:
  HYPRSPACES_BUILD_DIR     Build directory (default: build)
  HYPRSPACES_INSTALL_DIR   Install directory (default: ~/.local/share/hyprspaces)
  HYPRSPACES_HYPRLAND_CONF Hyprland config (default: ~/.config/hypr/hyprland.conf)
  HYPRSPACES_PLUGIN_CONF   Autoload conf (default: ~/.config/hypr/hyprspaces-plugin.conf)
EOF
}

build_plugin() {
    cmake -S "$PROJECT_DIR" -B "$PROJECT_DIR/$build_dir" >/dev/null
    cmake --build "$PROJECT_DIR/$build_dir"
}

install_plugin() {
    local built="$PROJECT_DIR/$build_dir/hyprspaces.so"
    if [[ ! -f "$built" ]]; then
        echo "error: built plugin not found: $built" >&2
        exit 1
    fi

    install -Dm 0644 "$built" "$plugin_path"
}

write_autoload_conf() {
    mkdir -p "$(dirname "$autoload_conf")"
    cat >"$autoload_conf" <<EOF
# Generated by scripts/plugin-install.sh
plugin = $plugin_path
EOF
}

ensure_source_line() {
    local source_line="source = $autoload_conf"
    mkdir -p "$(dirname "$hyprland_conf")"

    if [[ ! -f "$hyprland_conf" ]]; then
        printf '%s\n' "$source_line" >"$hyprland_conf"
        return 0
    fi

    if ! grep -Fxq "$source_line" "$hyprland_conf"; then
        printf '\n%s\n' "$source_line" >>"$hyprland_conf"
    fi
}

remove_source_line() {
    local source_line="source = $autoload_conf"
    if [[ ! -f "$hyprland_conf" ]]; then
        return 0
    fi

    if ! grep -Fxq "$source_line" "$hyprland_conf"; then
        return 0
    fi

    local tmp
    tmp=$(mktemp)
    grep -Fxv "$source_line" "$hyprland_conf" >"$tmp"
    mv "$tmp" "$hyprland_conf"
}

try_hyprctl() {
    if ! command -v hyprctl >/dev/null 2>&1; then
        echo "warning: hyprctl not found; skipping live reload" >&2
        return 0
    fi

    if ! hyprctl "$@"; then
        echo "warning: hyprctl failed; run inside Hyprland or set HYPRLAND_INSTANCE_SIGNATURE" >&2
        return 0
    fi
}

enable_autoload() {
    if [[ ! -f "$plugin_path" ]]; then
        echo "error: plugin not installed at $plugin_path" >&2
        exit 1
    fi

    write_autoload_conf
    ensure_source_line
}

disable_autoload() {
    remove_source_line
}

load_plugin_now() {
    try_hyprctl plugin load "$plugin_path"
}

unload_plugin_now() {
    try_hyprctl plugin unload "$plugin_path"
}

command="${1:-}"

case "$command" in
    install)
        build_plugin
        install_plugin
        enable_autoload
        load_plugin_now
        ;;
    enable)
        enable_autoload
        load_plugin_now
        ;;
    disable)
        disable_autoload
        unload_plugin_now
        ;;
    remove)
        disable_autoload
        unload_plugin_now
        rm -f "$autoload_conf" "$plugin_path"
        ;;
    -h|--help|help)
        usage
        ;;
    *)
        usage
        exit 1
        ;;
esac
